### ISSUE TITLE
what is the pytorch version?

### ISSUE THREAD

**Issue by Jxu-Thu** [automl/nasbench-1shot1#3]
Can you provide the necessary info for building the environment? 
e.g. pytorch version

**Comment by Jxu-Thu** [comment]
I find the warning as follows:

UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule.See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate

So I suspect you use the pytorch version <1.1.0.

**Comment by JulienSiems** [comment]
Indeed, for the experiments of the paper we were using PyTorch 1.0. We are currently in the process of restructuring the repo and will an updated requirements.txt then!

**Comment by Jxu-Thu** [comment]
but when I change to pytorch==1.0.1 (torchvision==0.2.2)
will find the error as follows:

from torchvision.datasets import VisionDataset
ImportError: cannot import name 'VisionDataset'

the VisionDataset in  repo requires torchvision>=0.3.0 and torch>=1.1.0 

Maybe we should use pytorch >=1.1 ?

Thanks for your kind reply!
