### ISSUE TITLE
how to reproduce the fig.5 in the paper

### ISSUE THREAD

**Issue by linnanwang** [automl/nasbench-1shot1#4]
Hello there,

Thank you for making the code public. I have a quick question, is the hyper-parameters in optimizer/bohb_one_shot/master and worker same as the one used in producing the Fig.5 in the paper? Thank you.

**Comment by arberzela** [comment]
Hello Linnan,

Thank you for your interest in our paper. Yes, those hyperparameters are the same we used to produce the Fig. 5 in the paper. You can run all `bohb_one_shot` experiments by executing this bash script [here](https://github.com/automl/nasbench-1shot1/blob/master/cluster_scripts/bohb_one_shot_scripts/start_exp.sh)

Cheers,
Arber
