### ISSUE TITLE
Refactor progress

### ISSUE THREAD

**Issue by martinferianc** [automl/nasbench-1shot1#6]
Hi! I think this is a very useful branch of research and I wanted to ask about the state of the refactor. I wanted to use the code myself, but to be honest, I got lost after 3 full days of looking at it and I decided to wait for the refactored version. Thanks!

**Comment by JulienSiems** [comment]
Hi @martinferianc, 
We got caught up in a different project, which is the reason for the delay. 
We are planning to release a new version relatively soon, but haven't had a chance to make a concrete deadline yet. 

Could you maybe point out what you wanted to try? E.g. did you want to try a new optimizer? 
In that case I coud already give you some guidelines on what to do.

Best, 
Julien

**Comment by martinferianc** [comment]
Hi @JulienSiems, thank you for getting back to me so quickly, and on the other hand, I apologise for my late reply. Essentially, yes I would like to add a new DARTS-like optimizer, however, I will need to build a custom loss function for it. On a high-level what should be aware of then? Thank you very much!

**Comment by JulienSiems** [comment]
Hi @martinferianc, no problem hope I can help you. I guess a good starting point would be the implementations of gdas and [pc-darts](https://github.com/automl/nasbench-1shot1/blob/master/optimizers/pc_darts/model_search.py) These reuse the darts search space code but add their respective mixed-op changes. The loss function of the one-shot model you can change inside the Network class. Once the search works you can then evaluate all architectures recorded after each epoch via [this](https://github.com/automl/nasbench-1shot1/blob/master/nasbench_analysis/eval_darts_one_shot_model_in_nasbench.py) script . Let me know if that helps!

**Comment by martinferianc** [comment]
Thank you @JulienSiems, I will get to it and hopefully open up a PR with my method soon. Thank you again!

**Comment by JulienSiems** [comment]
Great, let me know if you have any other questions!

**Comment by martinferianc** [comment]
Hi @JulienSiems! Thank you again for your help I think I got it all working :) ! I have two questions: 1. (probably dumb) The output that I get as a query from the nasbench wrapper for my chosen architecture is a test regret that is computed with respect to the best architecture right? 2. Is it possible to obtain the comparison data that you have used in your paper to create similar plots, but also with my method, such that I do not need to rerun everything for all the compared methods? Thank you!

**Comment by JulienSiems** [comment]
Hi @martinferianc! Sorry for the late response! 1.) The nasbench wrapper will only give you the test error, to get the regret check, check the search space description for the search space in which you search e.g. [search space 3](https://github.com/automl/nasbench-1shot1/blob/master/nasbench_analysis/search_spaces/search_space_3.py). We precomputed the lowest test error in the respective subsets of nasbench-101 and hardcoded them here. 
2.) Good point, I will have a look at how I can best export the one-shot trajectories or are you interested in the HPO analysis at the end of the paper?
Best and hope this helps!

**Comment by martinferianc** [comment]
Hi @JulienSiems! In general, I am asking about 2) because I have an idea that could improve all the gradient-based methods and I wanted to do a comparison of pre and post improvement. Actually, I would be very happy if you would be interested in it in more detail and perhaps it could lead to some collaboration. Since you are an author of this benchmark, I think with you this work could be then done 10x faster. Let me know what you think :). Thank you!

**Comment by JulienSiems** [comment]
Hi @martinferianc, Interesting! Let's chat via email siemsj@cs.uni-freiburg.de. Closing this issue for now :)

**Comment by martinferianc** [comment]
Hi Julien, I hope that you are doing well. I sent you an e-mail :)
