### ISSUE TITLE
pls check

### ISSUE THREAD

**Issue by solopku** [automl/nasbench-1shot1#7]
https://github.com/automl/nasbench-1shot1/blob/cb0f0ec61ce8b37f8e2d0f2728c3ef0b9ec81bf1/nasbench_analysis/search_spaces/search_space.py#L187

this line should check `col_idx > 0` instead of `col_sum > 0`.

the error makes many of the generated adj matrixes not conform to the `num_parents_per_node` constraint for those nodes of exactly **zero** parents, and thus and resultant architectures not in the defined search spaces.
 
you can print the adj matrixes generated by `generate_search_space_without_loose_ends()` and see the error.

**Comment by JulienSiems** [comment]
Hi @solopku, 

Having a look at this!

Best, 
Julien
